'use strict';

module.exports = {
  //ACTION CONSTANTS
  action: {
    //NavBar
    LOGOUT: 'LOGOUT',
    NAV_LOGIN: 'NAV_LOGIN',

    //Login
    LOGIN: 'LOGIN',
    NAV_STAGING: 'NAV_STAGING',
    IS_LOGGED_IN: 'IS_LOGGED_IN',
    IS_LOGGED_OUT: 'IS_LOGGED_OUT',

    //Staging
    NAV_ARENA: 'NAV_ARENA',

    //Arena
    GET_PROBLEM: 'GET_PROBLEM',
    GET_PROBLEM_SUCCESS: 'GET_PROBLEM_SUCCESS',
    GET_PROBLEM_ERROR: 'GET_PROBLEM_ERROR',
    SUBMIT_PROBLEM: 'SUBMIT_PROBLEM',
    SUBMIT_PROBLEM_WRONG: 'SUBMIT_PROBLEM_WRONG',
    SUBMIT_PROBLEM_SUCCESS: 'SUBMIT_PROBLEM_SUCCESS',
    NAV_LEADERBOARD: 'NAV_LEADERBOARD',

    //Arena - Sockets
    ENTER_ROOM: 'ENTER_ROOM',
    PROBLEM_START: 'PROBLEM_START',
    EXIT_ROOM: 'EXIT_ROOM',
    OPPONENT_FINISH: 'OPPONENT_FINISH',
    OPPONENT_KEYSTROKE: 'OPPONENT_KEYSTROKE',

    //Leaderboard
    GET_LEADERBOARD: 'GET_LEADERBOARD',
    GET_LEADERBOARD_SUCCESS: 'GET_LEADERBOARD_SUCCESS',
    GET_LEADERBOARD_ERROR: 'GET_LEADERBOARD_ERROR'
  },

  //VIEW CONSTANTS
  view: {
    LOGIN: 'LOGIN',
    STAGING: 'STAGING',
    ARENA: 'ARENA',
    LEADERBOARD: 'LEADERBOARD'
  }
}
